/** Shared look for the original wizard town (not any trademarked franchise). */
export const STYLE = [
  "Soft clay-like 3D isometric illustration, rounded matte surfaces, gentle directional light from upper-left.",
  "Original British wizarding village mood: dusk navy sky, warm amber window glow, cobblestone, ivy, brass lamps.",
  "Buildings vary in facade color, silhouette, and roof type — do not repeat the same grey-slate gable on every house.",
  "Do not use real franchise names, logos, or copyrighted characters.",
  "No summer beach pastels, no photorealism, no watermark, no readable text, no UI chrome.",
].join(" ");

export const CUTOUT =
  "Single isolated building, full body visible, centered, small contact shadow under the footprint only. Solid flat black background (#000000), no ground plane, no grass, no night sky, no other buildings. Isometric 2.5D camera matching the attached town map.";

export const FROM_MAP = [
  "Use the attached painted town map as the ONLY layout and style reference: dusk navy sky, crescent moon, clay-like 3D, cobble plaza, winding river, stone bridge, pond with a small dock, rolling dark hills, warm lanterns.",
  "Keep the same camera angle, proportions, and lighting. Do not invent a new valley.",
].join(" ");

export const SCENE =
  "Interior or close courtyard view, 3:2 landscape, subject in the center 70%. Soft clay 3D, dusk or lamplight. No UI, no watermark, no readable signage.";

/** Terrain-only: more land, more empty hard pads, camera pulled back. */
export const TERRAIN = [
  "Pull the isometric camera BACK so this is a spacious valley map, not a cramped postcard.",
  "Buildable LAND must fill about 75% of the frame. Water is only a thin crescent lake plus a narrow north strip — not an ocean.",
  "Leave wide unused moss fields and hinterland so later buildings have room.",
  "Paint 28 to 32 discrete HARD BUILDING PADS: pale flagstone, cut cobble, or packed-gravel rectangles with crisp edges.",
  "Each pad is empty, large, and isolated, big enough for one isometric hall or house, with walking space around it.",
  "No grass, flowers, or trees ON the pads. Soft moss and hedges only between pads.",
  "Cluster pads into districts: 8 town-square lots, 6 east-hill terrace lots, 5 south-promenade quay lots, 4 north-ridge lots, 6 west-island campus courtyards, plus 3–5 spare hinterland lots.",
  "Connect pads with cobble lanes. Still NO buildings, NO towers, NO houses, NO boats with cabins, NO people.",
].join(" ");

/** For finished town views: keep layout, vary the buildings. */
export const VARIETY = [
  "Keep the same spacious valley layout and dusk light, but make every landmark visually distinct.",
  "Mix facade colors: honey timber, pale limestone, rose brick, moss-green plaster, butter cream, dusk-blue wash, copper-trimmed stone.",
  "Mix silhouettes: wide civic hall, skinny towers, squat shops, L-shaped inn, round cottage, stepped terrace house, long school hall.",
  "Mix roofs: steep slate gable, red-clay tile, verdigris copper dome, thatch, fish-scale shingles, onion cap, stepped gable, one glass greenhouse roof.",
  "Neighboring buildings must not share the same color family or roof type.",
  "No parchment frame, no map border, no people.",
].join(" ");

/**
 * @typedef {object} ArtEntry
 * @property {string} id
 * @property {string} file
 * @property {'terrain'|'cutout'|'scene'|'scroll'|'prop'|'brand'} kind
 * @property {number} width
 * @property {number} height
 * @property {boolean} transparent
 * @property {string} prompt
 */

/** @type {ArtEntry[]} */
export const CATALOG = [
  {
    id: "map-base-ext",
    file: "map-base-ext.png",
    kind: "terrain",
    width: 3600,
    height: 2520,
    transparent: false,
    prompt: `${STYLE} ${FROM_MAP} Edit the attached map into TERRAIN ONLY. Remove every building, tower, house, chimney stack, person, and cabin boat. Keep hills, river, pond, dock, cobble plaza, dirt paths, trees, lantern posts, moon and sky. Where each building stood, leave a clean empty HARD PAD (flagstone or cobble) matching that footprint, no grass on the pad. Same dusk. No parchment frame, no UI, no readable text.`,
  },
  {
    id: "map-base",
    file: "map-base.png",
    kind: "terrain",
    width: 3600,
    height: 2400,
    transparent: false,
    prompt: `${STYLE} ${TERRAIN} Same spacious wizard-town terrain as the extended map but cropped off the north water strip. Native canvas 3600x2400. Empty hard pads only, no buildings.`,
  },
  {
    id: "map-full",
    file: "map-full.png",
    kind: "terrain",
    width: 3600,
    height: 2520,
    transparent: false,
    prompt: `${STYLE} ${VARIETY} Complete isometric postcard of a ROOMY wizard town on a large valley canvas 3600x2520. Camera pulled back. INCLUDING many landmarks sitting on separate hard pads with space between them: town hall, lakeside theater, tavern, apothecary, gallery, tea shop, owl tower, book tower, rune workshop, herb cottage, leaning wizard tower, mist inn, three lane houses, extra lane cottages, school island with hall, astronomy tower, and several more shops. Do not cram buildings together. Cohesive dusk lighting. Passport cover illustration.`,
  },

  {
    id: "b-townhall",
    file: "b-townhall.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${FROM_MAP} Recreate the civic hall from the reference: pale stone, central gable or clock, slightly grand, mixed roof (slate or copper trim), warm windows. One building only. Not a castle.`,
  },
  {
    id: "b-theater",
    file: "b-theater.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Open-air lakeside theater carved into a giant scallop shell, tiered peach-and-mint seating, small crescent-moon stage prop, fairy lights on white posts.`,
  },
  {
    id: "b-livehouse",
    file: "b-livehouse.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${FROM_MAP} Recreate the timber-framed tavern from the reference: plaster and beams, thatch or clay-tile roof, honey windows, barrels by the door, chimney smoke. One building only.`,
  },
  {
    id: "b-store",
    file: "b-store.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Crooked apothecary named by look not letters: leaning timber shop, jars and cauldrons in windows, one black shop cat on a crate, a single mysterious key over the door.`,
  },
  {
    id: "b-gallery",
    file: "b-gallery.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Stacked pink-stone cube gallery, tall windows with framed portraits faintly visible inside, photogenic staircase on the side.`,
  },
  {
    id: "b-coffee",
    file: "b-coffee.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Cauldron-bottom tea house shaped like a plump cup or kettle, steam, terrace umbrellas, soft cream and copper.`,
  },
  {
    id: "b-radio",
    file: "b-radio.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Owl Wireless hut: butter-yellow cabin, candy-striped broadcasting tower, owl perches, glowing beacon when a request is on air.`,
  },
  {
    id: "b-library",
    file: "b-library.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Forbidden-book tower built like a stack of giant tomes, weather vane, top-floor windows shuttered with iron lattice.`,
  },
  {
    id: "b-designlab",
    file: "b-designlab.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Rune workshop with glass roof, floating paper charms, a ring of carved runes, pencil-shaving warmth, salt air.`,
  },
  {
    id: "b-apple",
    file: "b-apple.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Herb-cottage with a round orchard-red roof like an apple, greenhouse lean-to, hanging herb bundles, one large leaf on the roof.`,
  },
  {
    id: "b-magic",
    file: "b-magic.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${FROM_MAP} Recreate the round stone tower with a conical copper roof and a small wooden balcony from the reference. One tower only, full body, black background.`,
  },
  {
    id: "b-hotel",
    file: "b-hotel.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Mist-harbor inn, tiered peach terraces, every balcony facing the lake, star-shaped potion pool on a terrace.`,
  },
  {
    id: "b-villas",
    file: "b-villas.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Three sister wizard houses sharing one garden: mint, lilac, and butter facades, one lemon-like potion tree, bunting between roofs.`,
  },
  {
    id: "i-pavilion",
    file: "i-pavilion.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} School great-hall exterior on an island: long stone hall, tall windows, slate roof, no castle sprawl, one lanterned entrance.`,
  },
  {
    id: "i-lighthouse",
    file: "i-lighthouse.png",
    kind: "cutout",
    width: 1024,
    height: 1536,
    transparent: true,
    prompt: `${STYLE} Isolated tall astronomy tower, portrait 2:3, solid black background. Spiral windows, bronze dome, faint beam. Isometric, no other buildings.`,
  },

  {
    id: "scene-townhall",
    file: "scene-townhall.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Council chamber interior: slow clock, potion-flower fountain visible through doors, warm wood benches.`,
  },
  {
    id: "scene-theater",
    file: "scene-theater.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Shell-stage at dusk, crescent moon prop, empty scallop seats, lake beyond.`,
  },
  {
    id: "scene-livehouse",
    file: "scene-livehouse.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Night Owl Tavern interior: oak bar, barrels, hearth, chalkboard menu with unreadable scribbles, honey lamps.`,
  },
  {
    id: "scene-store",
    file: "scene-store.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Apothecary interior: jars, one key in a glass case, cat on the counter.`,
  },
  {
    id: "scene-gallery",
    file: "scene-gallery.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Portrait hall, paintings that seem mid-blink, photogenic staircase.`,
  },
  {
    id: "scene-coffee",
    file: "scene-coffee.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Tea-house interior, steam, borrow-a-book shelf, cauldron-shaped cups.`,
  },
  {
    id: "scene-radio",
    file: "scene-radio.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Tiny broadcast booth, owl at the window, glowing request lamp.`,
  },
  {
    id: "scene-library",
    file: "scene-library.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Spiral stacks, iron grate on the top floor, moonlight.`,
  },
  {
    id: "scene-designlab",
    file: "scene-designlab.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Rune bench, hovering paper charms, glass roof night sky.`,
  },
  {
    id: "scene-apple",
    file: "scene-apple.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Herb kitchen, drying racks, pie-warm oven that is not in a fruit core.`,
  },
  {
    id: "scene-magic",
    file: "scene-magic.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Tilted room, doors to nowhere, sparkles, a cat on the banister.`,
  },
  {
    id: "scene-hotel",
    file: "scene-hotel.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Inn lobby, jasmine-scent implied by flowers, star pool visible through glass.`,
  },
  {
    id: "scene-villas",
    file: "scene-villas.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Shared garden of three houses, potion-lemon tree, croquet hoops.`,
  },
  {
    id: "scene-isle",
    file: "scene-isle.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} School courtyard overview: moving-stair hint in a distant window, lanterns, lake edge.`,
  },

  {
    id: "isle-pier-pano",
    file: "isle-pier-pano.png",
    kind: "scroll",
    width: 2048,
    height: 1152,
    transparent: false,
    prompt: `${STYLE} Ultra-wide 16:9 cinematic still of a stone causeway and iron school gates over dark water, dusk, no readable text, no logos.`,
  },
  {
    id: "isle-pavilion-scene",
    file: "isle-pavilion-scene.png",
    kind: "scroll",
    width: 2048,
    height: 1152,
    transparent: false,
    prompt: `${STYLE} Ultra-wide great hall: long tables, candle-floating feel without copying any film set, starry ceiling suggestion.`,
  },
  {
    id: "isle-sunset-scene",
    file: "isle-sunset-scene.png",
    kind: "scroll",
    width: 2048,
    height: 1152,
    transparent: false,
    prompt: `${STYLE} Ultra-wide lakeside training pitch at golden hour, broom-like training rings (abstract hoops, not branded sports), applause-ready terraces.`,
  },
  {
    id: "isle-lighthouse-scene",
    file: "isle-lighthouse-scene.png",
    kind: "scroll",
    width: 1024,
    height: 1536,
    transparent: false,
    prompt: `${STYLE} Tall 2:3 climb inside an astronomy tower, spiral stair, bronze instruments, night sky slit.`,
  },

  {
    id: "prop-boats",
    file: "prop-boats.png",
    kind: "prop",
    width: 1536,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} Isolated cluster of small lake skiffs / tiny flying- punt silhouettes, RGBA-ready, solid black background, no shoreline.`,
  },
  {
    id: "ferry",
    file: "ferry.png",
    kind: "prop",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${STYLE} School ferry crossing dusk water, 3:2 hero shot, lanterns, no logos.`,
  },
  {
    id: "tex-paper",
    file: "tex-paper.jpg",
    kind: "prop",
    width: 1024,
    height: 1024,
    transparent: false,
    prompt: "Seamless tileable parchment texture, warm cream, faint fiber, no text, no illustration, square.",
  },
  {
    id: "tex-wood",
    file: "tex-wood.jpg",
    kind: "prop",
    width: 1024,
    height: 1024,
    transparent: false,
    prompt: "Seamless tileable dark oak wood texture, tavern table, square, no text.",
  },
  {
    id: "logo",
    file: "logo.svg",
    kind: "brand",
    width: 512,
    height: 512,
    transparent: true,
    prompt: `${STYLE} Simple town crest icon: owl + lake crescent, flat vector feel, centered, no letters.`,
  },
  {
    id: "cursor",
    file: "cursor.png",
    kind: "brand",
    width: 32,
    height: 32,
    transparent: true,
    prompt: "Tiny 32x32 wand-tip cursor, hot spot upper-left, transparent, very simple.",
  },
  {
    id: "cursor@2x",
    file: "cursor@2x.png",
    kind: "brand",
    width: 64,
    height: 64,
    transparent: true,
    prompt: "Tiny 64x64 wand-tip cursor, transparent, same as 32px version.",
  },
];

export function byId(id) {
  return CATALOG.find((e) => e.id === id);
}

export const PREVIEW_IDS = ["map-base-ext", "b-townhall", "b-livehouse", "b-magic"];
