/** Shared look for the original wizard town (not any trademarked franchise). */
export const STYLE = [
  "Soft clay-like 3D isometric illustration, rounded matte surfaces, gentle directional light from upper-left.",
  "Original British wizarding village mood: dusk navy sky, warm amber window glow, cobblestone, ivy, brass lamps.",
  "Buildings vary in facade color, silhouette, and roof type — do not repeat the same grey-slate gable on every house.",
  "Do not use real franchise names, logos, or copyrighted characters.",
  "No summer beach pastels, no photorealism, no watermark, no readable text, no UI chrome.",
].join(" ");

export const CUTOUT =
  "Single isolated building, full body visible, centered, small contact shadow under the footprint only. Solid flat black background (#000000), no ground plane, no grass, no night sky, no other buildings.";

export const CUTOUT_FROM_MAP = [
  "Match the attached town map: same 3/4 isometric camera (not a flatter product shot), same clay-3D dusk lighting, same warm window glow.",
  "Extract ONE landmark exactly as it sits in that painting — same silhouette, same roof pitch, same materials. Do not invent a new design, do not rotate, do not flatten to a front elevation.",
].join(" ");

export const FROM_MAP = [
  "The attached painted town map is the ONLY reference. Match it as an in-place edit of the SAME SHOT.",
  "Lock camera: identical 3/4 isometric angle, identical framing, identical horizon line, identical crescent-moon position. Do not tilt, do not zoom out, do not rotate, do not pull the camera back.",
  "Keep dusk navy sky, cobble plaza, winding river, stone bridge, pond with a small dock, rolling dark hills, warm lanterns.",
].join(" ");

export const SCENE =
  "Interior or close courtyard view, 3:2 landscape, subject in the center 70%. Soft clay 3D, dusk or lamplight. No UI, no watermark, no readable signage.";

/** README brand frames: same town, no summer-map pastels, no letters (titles live in Markdown). */
export const README_STYLE = [
  STYLE,
  "GitHub README illustration, cinematic dusk editorial, rounded 28px-feel frame.",
  "Palette: dusk navy sky #1B2240, warm amber window glow #C9A227, cream stone #F4EDE0, moss #7C8C6A.",
  "Motif: lanterns and lit windows in an original wizarding village. Not a beach town, not seashells, not summer pastels.",
  "No logos, no badges, no UI chrome, no watermarks, no readable letters or numbers of any language.",
].join(" ");

/** Terrain-only: more land, more empty hard pads, camera pulled back. */
export const TERRAIN = [
  "Pull the isometric camera BACK so this is a spacious valley map, not a cramped postcard.",
  "Buildable LAND must fill about 75% of the frame. Water is only a thin crescent lake plus a narrow north strip — not an ocean.",
  "Leave wide unused moss fields and hinterland so later buildings have room.",
  "Paint 28 to 32 discrete HARD BUILDING PADS: pale flagstone, cut cobble, or packed-gravel rectangles with crisp edges.",
  "Each pad is empty, large, and isolated, big enough for one isometric hall or house, with walking space around it.",
  "No grass, flowers, or trees ON the pads. Soft moss and hedges only between pads.",
  "Cluster pads into districts: 8 town-square lots, 6 east-hill terrace lots, 5 south-promenade quay lots, 4 north-ridge lots, 6 west-island campus courtyards, plus 3–5 spare hinterland lots.",
  "Connect pads with cobble lanes. Still NO buildings, NO towers, NO houses, NO boats with cabins, NO people.",
].join(" ");

/** Pad the original map-full: more woods/water, buildings locked. */
export const ENV_PAD = [
  "OUTPAINT the blurred margins of the attached image into finished environment. The sharp town is FINAL — do not redraw, move, or restyle any building.",
  "Paint NEW seamless environment that continues naturally from the town edges, same clay-3D dusk brush, same tree shapes, same dusk lighting. Do not tile or copy-paste strips.",
  "LEFT margin: continue the same dusk valley — rounded night trees, distant hills, a little more dark grass. No new buildings, no extra cottages, no ruins.",
  "RIGHT / BOTTOM / TOP: keep the existing woods, pond, dock, and sky continuous; only fill leftover blur. Only ONE crescent moon.",
  "No autumn trees, no parchment border, no UI. Seamless blending with the town edges.",
].join(" ");

/** For finished town views: keep layout, vary the buildings. */
export const VARIETY = [
  "Keep the same spacious valley layout and dusk light, but make every landmark visually distinct.",
  "Mix facade colors: honey timber, pale limestone, rose brick, moss-green plaster, butter cream, dusk-blue wash, copper-trimmed stone.",
  "Mix silhouettes: wide civic hall, skinny towers, squat shops, L-shaped inn, round cottage, stepped terrace house, long school hall.",
  "Mix roofs: steep slate gable, red-clay tile, verdigris copper dome, thatch, fish-scale shingles, onion cap, stepped gable, one glass greenhouse roof.",
  "Neighboring buildings must not share the same color family or roof type.",
  "No parchment frame, no map border, no people.",
].join(" ");

/**
 * @typedef {object} ArtEntry
 * @property {string} id
 * @property {string} file
 * @property {'terrain'|'cutout'|'scene'|'scroll'|'prop'|'brand'|'readme'} kind
 * @property {number} width
 * @property {number} height
 * @property {boolean} transparent
 * @property {string} [imageSize]
 * @property {string} [publishTo] copy generated bytes here (repo-relative); still writes art-preview/
 * @property {string} prompt
 */

/** @type {ArtEntry[]} */
export const CATALOG = [
  {
    id: "map-base-ext",
    file: "map-base-ext.png",
    kind: "terrain",
    width: 2400,
    height: 1792,
    transparent: false,
    imageSize: "2K",
    prompt: `${STYLE} ${FROM_MAP} IN-PLACE EDIT of the attached map into TERRAIN ONLY. Keep the same sky, moon, hills, trees, river, pond, docks, lantern posts, cobble plaza and paths. Remove every building, tower, house, chimney, copper dome, glasshouse, and outdoor cafe furniture. Where each building stood, leave a clean empty HARD PAD (flagstone or cobble) matching that exact footprint and shape. No grass on the pads. Do not add extra pads. Do not zoom out or reframe. No parchment, no UI, no readable text.`,
  },
  {
    id: "map-base",
    file: "map-base.png",
    kind: "terrain",
    width: 3600,
    height: 2400,
    transparent: false,
    prompt: `${STYLE} ${TERRAIN} Same spacious wizard-town terrain as the extended map but cropped off the north water strip. Native canvas 3600x2400. Empty hard pads only, no buildings.`,
  },
  {
    id: "map-full",
    file: "map-full.png",
    kind: "terrain",
    width: 3600,
    height: 2520,
    transparent: false,
    prompt: `${STYLE} ${VARIETY} Complete isometric postcard of a ROOMY wizard town on a large valley canvas 3600x2520. Camera pulled back. INCLUDING many landmarks sitting on separate hard pads with space between them: town hall, lakeside theater, tavern, apothecary, gallery, tea shop, owl tower, book tower, rune workshop, herb cottage, leaning wizard tower, mist inn, three lane houses, extra lane cottages, school island with hall, astronomy tower, and several more shops. Do not cram buildings together. Cohesive dusk lighting. Passport cover illustration.`,
  },

  {
    id: "map-full-a",
    file: "map-full-a.png",
    kind: "terrain",
    width: 1480,
    height: 980,
    transparent: false,
    imageSize: "2K",
    prompt: `${STYLE} ${ENV_PAD}`,
  },
  {
    id: "map-full-b",
    file: "map-full-b.png",
    kind: "terrain",
    width: 1480,
    height: 980,
    transparent: false,
    imageSize: "2K",
    prompt: `${STYLE} ${ENV_PAD}`,
  },
  {
    id: "map-full-c",
    file: "map-full-c.png",
    kind: "terrain",
    width: 1480,
    height: 980,
    transparent: false,
    imageSize: "2K",
    prompt: `${STYLE} ${ENV_PAD}`,
  },

  {
    id: "b-townhall",
    file: "b-townhall.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} The large reddish-brown timber civic hall WITH CLOCK TOWER sitting just ABOVE the central cobble plaza. Steep blue-grey shingles, warm windows, half-timber. One building only. Not a castle, not the copper-dome workshop.`,
  },
  {
    id: "b-theater",
    file: "b-theater.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Match the attached map's clay-3D dusk lighting and 3/4 isometric camera. The olive-green timber hall with a terracotta red-tile roof and a semicircular wooden stage-porch. ROTATE the building so the MAIN ENTRANCE and curved deck face BOTTOM-RIGHT of the frame (toward the southeast). Do not leave the porch facing bottom-left. One building only. Solid flat black background.`,
  },
  {
    id: "b-livehouse",
    file: "b-livehouse.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} The circular stone workshop-tavern at the BOTTOM of the central plaza: large copper dome, smoking chimney, outdoor round tables, warm windows. One building only. Not the clock hall, not a timber cottage.`,
  },
  {
    id: "b-store",
    file: "b-store.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} The unique cottage on the RIGHT of the plaza with a rounded beehive thatched roof and a tiny glass sunroom on the front. Shop-like, warm windows. One building only.`,
  },
  {
    id: "b-gallery",
    file: "b-gallery.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} Extract the NARROW pale-yellow / cream townhouse from the RIGHT-SIDE residential row (yellow, then blue, then grey houses). Steep gable, timber or plaster walls, many small glowing windows. Keep the painted facing and roof pitch. One slim house only — not the greenhouse, not the thatched shop.`,
  },
  {
    id: "b-coffee",
    file: "b-coffee.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} Extract the cream house with the complex multi-layered yellow-tiled roof and several chimneys, sitting just RIGHT of the central clock hall, with a small outdoor terrace. Keep the painted facing, roof stack, and materials. Cozy tea-house. One building only — not the copper-dome tavern, not the greenhouse.`,
  },
  {
    id: "b-radio",
    file: "b-radio.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} The cylindrical stone turret with a copper onion-bulb dome in the LEFT cluster of tall houses. One tower only. Not the spiral-stair tower.`,
  },
  {
    id: "b-library",
    file: "b-library.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} The tall dark jagged timber tower with a sharp gothic spire, standing LEFT of the spiral-stair tower behind the clock hall. One tower only.`,
  },
  {
    id: "b-designlab",
    file: "b-designlab.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} From the attached map, extract the glass greenhouse / conservatory on the RIGHT of the town: brick or pink-stone base, large faceted glass roof, warm interior glow. Keep the same isometric facing as painted. One building only — keep the attached-workshop look, not a palace of glass.`,
  },
  {
    id: "b-gallery-lab",
    file: "b-gallery-lab.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} Extract the RIGHT-SIDE row as ONE cluster: yellow house, blue-grey house, cream Dutch stepped-gable, plus the attached brick glasshouse behind them. Exact painted facing. Isolated cutout, black background.`,
  },
  {
    id: "b-apple",
    file: "b-apple.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} The blue-grey two-story cottage with two brick chimneys and steep dark gables, BOTTOM-RIGHT of the plaza, ivy on the wall. One building only.`,
  },
  {
    id: "b-magic",
    file: "b-magic.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} The cylindrical stone tower with an EXTERNAL WOODEN SPIRAL STAIRCASE and conical copper roof, sitting BEHIND the clock hall (not the far-right bridged tower). One tower only.`,
  },
  {
    id: "b-hotel",
    file: "b-hotel.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Sandstone gothic hall with tall glowing pointed-arch windows and a short stone-arch bridge stub extending from the RIGHT side toward a circular tower. Isolated hall only, black background.`,
  },
  {
    id: "b-villas",
    file: "b-villas.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} ${CUTOUT_FROM_MAP} From the attached map, extract the LEFT-SIDE ROW of three tall timber-framed sister houses with steep dark gables and ivy (the cluster above the olive-green hall). Keep the EXACT painted facing and roof direction — do not mirror, do not rotate. Three distinct houses sharing one garden, not one merged manor.`,
  },
  {
    id: "i-pavilion",
    file: "i-pavilion.png",
    kind: "cutout",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} ${CUTOUT} Circular stone tower with a conical copper roof on a small round cobble pad. Isolated tower only — no bridge, no walkway, no other buildings. Black background.`,
  },
  {
    id: "i-lighthouse",
    file: "i-lighthouse.png",
    kind: "cutout",
    width: 1024,
    height: 1536,
    transparent: true,
    prompt: `${STYLE} Isolated tall astronomy tower, portrait 2:3, solid black background. Spiral windows, bronze dome, faint beam. Isometric, no other buildings.`,
  },
  {
    id: "prop-hall-bridge",
    file: "prop-hall-bridge.png",
    kind: "prop",
    width: 1024,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} Isolated 3-arch stone footbridge, isometric, spanning bottom-left to top-right. Warm tan masonry, low parapets, moss at the piers. Solid black background, no buildings.`,
  },

  {
    id: "scene-townhall",
    file: "scene-townhall.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Council chamber interior: slow clock, potion-flower fountain visible through doors, warm wood benches.`,
  },
  {
    id: "scene-theater",
    file: "scene-theater.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Shell-stage at dusk, crescent moon prop, empty scallop seats, lake beyond.`,
  },
  {
    id: "scene-livehouse",
    file: "scene-livehouse.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Night Owl Tavern interior: oak bar, barrels, hearth, chalkboard menu with unreadable scribbles, honey lamps.`,
  },
  {
    id: "scene-store",
    file: "scene-store.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Apothecary interior: jars, one key in a glass case, cat on the counter.`,
  },
  {
    id: "scene-gallery",
    file: "scene-gallery.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Portrait hall, paintings that seem mid-blink, photogenic staircase.`,
  },
  {
    id: "scene-coffee",
    file: "scene-coffee.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Tea-house interior, steam, borrow-a-book shelf, cauldron-shaped cups.`,
  },
  {
    id: "scene-radio",
    file: "scene-radio.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Tiny broadcast booth, owl at the window, glowing request lamp.`,
  },
  {
    id: "scene-library",
    file: "scene-library.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Spiral stacks, iron grate on the top floor, moonlight.`,
  },
  {
    id: "scene-designlab",
    file: "scene-designlab.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Rune bench, hovering paper charms, glass roof night sky.`,
  },
  {
    id: "scene-apple",
    file: "scene-apple.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Herb kitchen, drying racks, pie-warm oven that is not in a fruit core.`,
  },
  {
    id: "scene-magic",
    file: "scene-magic.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Tilted room, doors to nowhere, sparkles, a cat on the banister.`,
  },
  {
    id: "scene-hotel",
    file: "scene-hotel.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Inn lobby, jasmine-scent implied by flowers, star pool visible through glass.`,
  },
  {
    id: "scene-villas",
    file: "scene-villas.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} Shared garden of three houses, potion-lemon tree, croquet hoops.`,
  },
  {
    id: "scene-isle",
    file: "scene-isle.png",
    kind: "scene",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${SCENE} School courtyard overview: moving-stair hint in a distant window, lanterns, lake edge.`,
  },

  {
    id: "isle-pier-pano",
    file: "isle-pier-pano.png",
    kind: "scroll",
    width: 2048,
    height: 1152,
    transparent: false,
    prompt: `${STYLE} Ultra-wide 16:9 cinematic still of a stone causeway and iron school gates over dark water, dusk, no readable text, no logos.`,
  },
  {
    id: "isle-pavilion-scene",
    file: "isle-pavilion-scene.png",
    kind: "scroll",
    width: 2048,
    height: 1152,
    transparent: false,
    prompt: `${STYLE} Ultra-wide great hall: long tables, candle-floating feel without copying any film set, starry ceiling suggestion.`,
  },
  {
    id: "isle-sunset-scene",
    file: "isle-sunset-scene.png",
    kind: "scroll",
    width: 2048,
    height: 1152,
    transparent: false,
    prompt: `${STYLE} Ultra-wide lakeside training pitch at golden hour, broom-like training rings (abstract hoops, not branded sports), applause-ready terraces.`,
  },
  {
    id: "isle-lighthouse-scene",
    file: "isle-lighthouse-scene.png",
    kind: "scroll",
    width: 1024,
    height: 1536,
    transparent: false,
    prompt: `${STYLE} Tall 2:3 climb inside an astronomy tower, spiral stair, bronze instruments, night sky slit.`,
  },

  {
    id: "prop-boats",
    file: "prop-boats.png",
    kind: "prop",
    width: 1536,
    height: 1024,
    transparent: true,
    prompt: `${STYLE} Isolated cluster of small lake skiffs / tiny flying- punt silhouettes, RGBA-ready, solid black background, no shoreline.`,
  },
  {
    id: "ferry",
    file: "ferry.png",
    kind: "prop",
    width: 1536,
    height: 1024,
    transparent: false,
    prompt: `${STYLE} School ferry crossing dusk water, 3:2 hero shot, lanterns, no logos.`,
  },
  {
    id: "tex-paper",
    file: "tex-paper.jpg",
    kind: "prop",
    width: 1024,
    height: 1024,
    transparent: false,
    prompt: "Seamless tileable parchment texture, warm cream, faint fiber, no text, no illustration, square.",
  },
  {
    id: "tex-wood",
    file: "tex-wood.jpg",
    kind: "prop",
    width: 1024,
    height: 1024,
    transparent: false,
    prompt: "Seamless tileable dark oak wood texture, tavern table, square, no text.",
  },
  {
    id: "logo",
    file: "logo.svg",
    kind: "brand",
    width: 512,
    height: 512,
    transparent: true,
    prompt: `${STYLE} Simple town crest icon: owl + lake crescent, flat vector feel, centered, no letters.`,
  },
  {
    id: "cursor",
    file: "cursor.png",
    kind: "brand",
    width: 32,
    height: 32,
    transparent: true,
    prompt: "Tiny 32x32 wand-tip cursor, hot spot upper-left, transparent, very simple.",
  },
  {
    id: "cursor@2x",
    file: "cursor@2x.png",
    kind: "brand",
    width: 64,
    height: 64,
    transparent: true,
    prompt: "Tiny 64x64 wand-tip cursor, transparent, same as 32px version.",
  },

  {
    id: "readme-hero",
    file: "readme-hero.png",
    kind: "readme",
    width: 1600,
    height: 640,
    transparent: false,
    imageSize: "2K",
    publishTo: "assets/readme/hero.png",
    prompt: `${README_STYLE} Ultra-wide 2.5:1 GitHub hero painting of Magic Town at dusk: a clay-3D isometric valley village with a clock-tower hall, copper-dome tavern, glass workshop, and a leaning wizard tower. Warm lanterns, crescent moon, cobble plaza, ivy. Empty of people. Full painted sky, not a cutout. Passport-cover energy without any letters.`,
  },
  {
    id: "readme-showcase",
    file: "readme-showcase.png",
    kind: "readme",
    width: 1600,
    height: 900,
    transparent: false,
    imageSize: "2K",
    publishTo: "assets/readme/showcase.png",
    prompt: `${README_STYLE} 16:9 proof board of Magic Town residents at work, arranged as five slightly overlapping clay-3D vignette windows on a dusk navy table: a clerk with tidy paper slips, a tea-house nutritionist with a cauldron cup, a tavern barkeeper, a rune workshop with hovering paper charms, a spiral library. Soft contact shadows. No screenshots, no letters, no beach collage.`,
  },
  {
    id: "readme-runtime",
    file: "readme-runtime.png",
    kind: "readme",
    width: 1600,
    height: 640,
    transparent: false,
    imageSize: "2K",
    publishTo: "assets/readme/runtime.png",
    prompt: `${README_STYLE} Ultra-wide 2.5:1 sequence strip of three dusk clay-3D beats in one painting, left to right, connected by a lantern-lit cobble path: (1) isometric town map on a table, (2) a brass town-pass token glowing on wood, (3) a visitor and a resident talking beside a warm window with a memory-drawer of paper slips. No letters, no UI, no computers with readable screens.`,
  },
  {
    id: "readme-section-agents",
    file: "readme-section-agents.png",
    kind: "readme",
    width: 1600,
    height: 280,
    transparent: false,
    publishTo: "assets/readme/section-agents.png",
    prompt: `${README_STYLE} Very short 6:1 cinematic banner: dusk cobble street, brass lanterns, a few glowing windows, ivy. Empty of people. Decorative GitHub section strip only. No letters.`,
  },
  {
    id: "readme-section-run",
    file: "readme-section-run.png",
    kind: "readme",
    width: 1600,
    height: 280,
    transparent: false,
    publishTo: "assets/readme/section-run.png",
    prompt: `${README_STYLE} Very short 6:1 cinematic banner: an oak door ajar onto a lamplit workshop, brass key on the threshold, warm interior glow. Decorative GitHub section strip only. No letters.`,
  },
];

export function byId(id) {
  return CATALOG.find((e) => e.id === id);
}

export const PREVIEW_IDS = ["map-base-ext", "b-townhall", "b-livehouse", "b-magic"];

/** Magic Town README brand frames. Full scenes — do not punch. */
export const README_IDS = [
  "readme-hero",
  "readme-showcase",
  "readme-runtime",
  "readme-section-agents",
  "readme-section-run",
];
