/**
 * Google Gemini image pipeline (GOOGLE_API_KEY only — do not also set GEMINI_API_KEY).
 * Usage:
 *   node scripts/art/generate.mjs --list
 *   node scripts/art/generate.mjs --dump
 *   node scripts/art/generate.mjs --probe
 *   node scripts/art/generate.mjs --preview
 *   node scripts/art/generate.mjs --ids map-base-ext,b-townhall,b-livehouse
 *
 * Writes to assets/art-preview/ (does not overwrite public/).
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import dns from "node:dns";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Agent } from "undici";
import { CATALOG, PREVIEW_IDS, byId } from "./catalog.mjs";

dns.setDefaultResultOrder("ipv4first");

const dispatcher = new Agent({
  connect: { timeout: 30_000, family: 4 },
});

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const OUT_DIR = path.join(root, "assets", "art-preview");
const GEMINI_ROOT = "https://generativelanguage.googleapis.com/v1beta";
const DEFAULT_MODEL = "gemini-3.1-flash-lite-image";
const FALLBACK_MODEL = "gemini-3.1-flash-image";
const REQUEST_MS = 120_000;
const RETRIES = 1;

async function loadDotEnv(filePath) {
  let text = "";
  try {
    text = await readFile(filePath, "utf8");
  } catch {
    return;
  }
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] == null || process.env[key] === "") {
      process.env[key] = value;
    }
  }
}

function parseArgs(argv) {
  const out = { list: false, dump: false, ids: [], kind: "", probe: false, ref: "" };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--list") out.list = true;
    else if (a === "--dump") out.dump = true;
    else if (a === "--probe") out.probe = true;
    else if (a === "--ids") out.ids = (argv[++i] ?? "").split(",").filter(Boolean);
    else if (a === "--kind") out.kind = argv[++i] ?? "";
    else if (a === "--preview") out.ids = [...PREVIEW_IDS];
    else if (a === "--ref") out.ref = argv[++i] ?? "";
  }
  return out;
}

function pickAspect(entry) {
  const ratio = entry.width / entry.height;
  if (Math.abs(ratio - 1) < 0.08) return "1:1";
  if (ratio >= 1.7) return "16:9";
  if (ratio > 1.05) return "4:3";
  if (ratio <= 0.6) return "9:16";
  return "3:4";
}

function pickImageSize() {
  return "1K";
}

async function gemini(apiKey, pathname, init) {
  const res = await fetch(`${GEMINI_ROOT}${pathname}`, {
    ...init,
    dispatcher,
    signal: init?.signal ?? AbortSignal.timeout(REQUEST_MS),
    headers: {
      "x-goog-api-key": apiKey,
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
  });
  const text = await res.text();
  let json;
  try {
    json = JSON.parse(text);
  } catch {
    json = { raw: text };
  }
  return { ok: res.ok, status: res.status, json };
}

function dumpPrompts() {
  const lines = [
    "# Art prompts",
    "",
    "Source of truth: `scripts/art/catalog.mjs`. Regenerated by `npm run art:prompts`.",
    "Shared style prefixes live in `STYLE` / `CUTOUT` / `SCENE`. Names stay blank.",
    "",
  ];
  for (const e of CATALOG) {
    lines.push(`## ${e.id}`);
    lines.push("");
    lines.push(`- file: \`${e.file}\``);
    lines.push(`- kind: ${e.kind}`);
    lines.push(`- size: ${e.width}×${e.height}`);
    lines.push(`- transparent: ${e.transparent}`);
    lines.push("");
    lines.push("```");
    lines.push(e.prompt);
    lines.push("```");
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

function extractInlineImage(json) {
  const parts = json?.candidates?.[0]?.content?.parts ?? [];
  for (const part of parts) {
    const inline = part.inlineData ?? part.inline_data;
    if (inline?.data) {
      return Buffer.from(inline.data, "base64");
    }
  }
  return null;
}

function errorMessage(json, status) {
  return (
    json?.error?.message ??
    json?.candidates?.[0]?.finishReason ??
    json?.promptFeedback?.blockReason ??
    JSON.stringify(json).slice(0, 400) ??
    `HTTP ${status}`
  );
}

function describeFetchError(err) {
  if (err?.name === "TimeoutError" || err?.name === "AbortError") {
    return `timeout ${REQUEST_MS / 1000}s`;
  }
  const cause = err?.cause?.message ?? err?.cause?.code ?? "";
  const msg = err instanceof Error ? err.message : String(err);
  return cause ? `${msg} (${cause})` : msg;
}

async function loadRefParts(refPath) {
  if (!refPath) return [];
  const abs = path.isAbsolute(refPath) ? refPath : path.join(root, refPath);
  const buf = await readFile(abs);
  const ext = path.extname(abs).toLowerCase();
  const mime = ext === ".jpg" || ext === ".jpeg" ? "image/jpeg" : "image/png";
  return [{ inlineData: { mimeType: mime, data: buf.toString("base64") } }];
}

async function requestImage(apiKey, model, entry, withSize, refParts) {
  const imageConfig = { aspectRatio: pickAspect(entry) };
  if (withSize) imageConfig.imageSize = pickImageSize();
  const parts = refParts.length
    ? [...refParts, { text: entry.prompt }]
    : [{ text: entry.prompt }];
  const body = {
    contents: [{ parts }],
    generationConfig: {
      responseModalities: ["TEXT", "IMAGE"],
      imageConfig,
    },
  };
  try {
    return await gemini(apiKey, `/models/${encodeURIComponent(model)}:generateContent`, {
      method: "POST",
      body: JSON.stringify(body),
    });
  } catch (err) {
    throw new Error(describeFetchError(err));
  }
}

async function generateOne(apiKey, model, entry, refParts) {
  let result = await requestImage(apiKey, model, entry, true, refParts);
  if (
    !result.ok &&
    /imageSize|image_size|Unknown name/i.test(errorMessage(result.json, result.status))
  ) {
    result = await requestImage(apiKey, model, entry, false, refParts);
  }
  const { ok, status, json } = result;
  if (!ok) {
    throw new Error(`HTTP ${status}: ${errorMessage(json, status)}`);
  }
  const buf = extractInlineImage(json);
  if (!buf) {
    throw new Error(`no image part: ${errorMessage(json, status)}`);
  }
  return buf;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function isBusy(msg) {
  return /503|high demand|UNAVAILABLE|429|RESOURCE_EXHAUSTED|timeout|fetch failed|ECONNRESET|UND_ERR/i.test(
    msg,
  );
}

async function generateWithFallback(apiKey, preferred, entry, refParts) {
  const models = [preferred];
  if (!refParts.length && FALLBACK_MODEL && FALLBACK_MODEL !== preferred) {
    models.push(FALLBACK_MODEL);
  }
  let lastErr;
  for (const model of models) {
    for (let attempt = 1; attempt <= RETRIES + 1; attempt++) {
      try {
        const buf = await generateOne(apiKey, model, entry, refParts);
        return { buf, model };
      } catch (err) {
        lastErr = err;
        const msg = err instanceof Error ? err.message : String(err);
        if (isBusy(msg) && attempt < RETRIES + 1) {
          await sleep(2000);
          continue;
        }
        if (/404|not found|NOT_FOUND|not supported|is not found/i.test(msg)) {
          break;
        }
        if (!isBusy(msg)) throw err;
      }
    }
  }
  throw lastErr ?? new Error("no image model available");
}

async function main() {
  const args = parseArgs(process.argv);
  await loadDotEnv(path.join(root, ".env"));
  // Avoid the @google/genai dual-key warning if someone later adds the SDK.
  delete process.env.GEMINI_API_KEY;

  const apiKey = process.env.GOOGLE_API_KEY ?? "";
  const imageModel = process.env.GOOGLE_IMAGE_MODEL || DEFAULT_MODEL;

  if (args.list) {
    for (const e of CATALOG) {
      console.log(`${e.id.padEnd(22)} ${e.kind.padEnd(8)} ${e.width}x${e.height}  ${e.file}`);
    }
    console.log(`\n${CATALOG.length} entries. Preview set: ${PREVIEW_IDS.join(", ")}`);
    return;
  }

  if (args.dump) {
    const dest = path.join(root, "scripts", "art", "PROMPTS.md");
    await writeFile(dest, dumpPrompts(), "utf8");
    console.log(`wrote ${dest} (${CATALOG.length} prompts)`);
    return;
  }

  if (!apiKey) {
    console.error("Missing GOOGLE_API_KEY (set in .env or the environment). Do not also set GEMINI_API_KEY.");
    process.exit(1);
  }

  if (args.probe) {
    const models = await gemini(apiKey, "/models", { method: "GET" });
    const names = (models.json?.models ?? [])
      .map((m) => (m.name ?? "").replace(/^models\//, ""))
      .filter((name) => /image|imagen|banana/i.test(name));
    console.log("GET /models", models.status, "image-ish:", names.join(", ") || "(none)");
    if (!models.ok) {
      console.log(JSON.stringify(models.json, null, 2).slice(0, 1500));
      process.exitCode = 1;
    }
    return;
  }

  let jobs = CATALOG;
  if (args.ids.length) {
    jobs = args.ids.map((id) => {
      const e = byId(id);
      if (!e) throw new Error(`unknown id: ${id}`);
      return e;
    });
  } else if (args.kind) {
    jobs = CATALOG.filter((e) => e.kind === args.kind);
  } else {
    jobs = PREVIEW_IDS.map((id) => byId(id)).filter(Boolean);
  }

  await mkdir(OUT_DIR, { recursive: true });
  const refParts = await loadRefParts(args.ref);
  console.log(
    `provider=gemini  model=${imageModel}  out=${OUT_DIR}  n=${jobs.length}` +
      (args.ref ? `  ref=${args.ref}` : ""),
  );

  for (const entry of jobs) {
    const dest = path.join(OUT_DIR, entry.file);
    process.stdout.write(`→ ${entry.id} ${pickAspect(entry)} 1K … `);
    try {
      const { buf, model } = await generateWithFallback(apiKey, imageModel, entry, refParts);
      await writeFile(dest, buf);
      console.log(`ok ${buf.length} bytes  (${model})`);
    } catch (err) {
      console.log("FAIL");
      console.error(`  ${err instanceof Error ? err.message : err}`);
      process.exitCode = 1;
    }
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
